### ISSUE TITLE
bugs in script

### ISSUE THREAD

**Issue by jreuben11** [JasonAtNvidia/JetsonTFBuild#11]
issue 1) **source ./configure on line 153 in wrong directory**
problem: the script changes working directory from `tensorflow` to `tensorflow/tensorflow` to apply the aarch64 patch on BUILD. need to change back `cd ..`, in order to execute `tensorflow/configure`.

**Comment by jreuben11** [comment]
issue 2) **patch is only partially applied**:
`tensorflow/contrib/lite/kernels/internal/BUILD` gets patched
but
`third_party/png.BUILD` does not get patched !
Had to manually patch to proceed.

**Comment by jreuben11** [comment]
issue 3) **copy libtensorflow_framework too**
`cp -r bazel-bin/tensorflow/libtensorflow_framework.so /usr/local/lib/`

**Comment by JasonAtNvidia** [comment]
please try the new script.  The raspberry pi support of TF 1.10 has removed the need to patch png.BUILD, there is still a patch that removes the --neon call in the build process.
