### ISSUE TITLE
Build tf `r1.8` fails on jetson.

### ISSUE THREAD

**Issue by Hanqing-Sun** [JasonAtNvidia/JetsonTFBuild#2]
This post is not quite an issue. :smile: According to tensorflow/tensorflow#18643, there are some problems to build tensorflow branch `r1.8` on aarch64 (Jetson TX1 & 2).
The error msg looks like:
`undefined reference to 'png_init_filter_functions_neon'`

I'm posting here just to let more know the workaround (pr: tensorflow/tensorflow/pull/19075):

Change file `third_party/png.BUILD` in tensorflow repo, near line 38:
add line:
`copts = ["-DPNG_ARM_NEON_OPT=0"],`
bellow line: `linkopts = ["-lm"],`

After the amendment, rerun the `BuildTensorFlow.sh` script or the `bazel build` cmd.

**Comment by timoonboru** [comment]
Hello , Could you sharing your experience with installing TensorFlow on TX2 ?
 I have flashed TX2 with Jetpack 3.2. 
"$ sudo bash BuildTensorFlow.sh" failed.
Or could you leave a way to contact?

**Comment by JasonAtNvidia** [comment]
@DefineFC 
I see google has included a "raspberry pi" fix in the master branch.  I'm hoping this automagically migrates and works with the TX2.  I am testing an update to my build script now.  Hopefully all is smooth.  Thank you for pointing this out.  I'm undecided about including a patch in my helperscript or just leaving it out and putting a warning about r1.8 being broken.

**Comment by Hanqing-Sun** [comment]
@timoonboru 
Just 
> Change file `third_party/png.BUILD` in tensorflow repo, near line 38:
> add line:
> `copts = ["-DPNG_ARM_NEON_OPT=0"]`,
> bellow line: `linkopts = ["-lm"]`,

And then, do what @JasonAtNvidia tells us to do. If you're still having trouble accomplishing, try `sudo bash BuildTensorFlow.sh -b r1.7` as described in this repo.

Read the doc very carefully and do exactly as told to. There is no magic.

**Comment by Hanqing-Sun** [comment]
@JasonAtNvidia Hoping tf will fix that issue painlessly, too.

Jason, did you really build the wheel for `Compute Capability 5.2, and 6.3` as described in `README.md`? IMHO, `Compute Capability 5.3, and 6.2` seems more common for Jetson.

**Comment by JasonAtNvidia** [comment]
> @DefineFC  It is a typo, it is 5.3 for the TX1 and 6.2 for TX2.  It would fail miserably if I tried building for CC6.3 because the Jetson is not capable of it.

**Comment by JasonAtNvidia** [comment]
Today I uploaded a git patch that takes care of the 2 files that need to be modified for a successful build.  I also posted updated links to TF 1.8.0 wheel binaries to use directly without the need to build TF yourself.
