### ISSUE TITLE
 TF v 1.7.0 on tx2

### ISSUE THREAD

**Issue by q1178847289** [JasonAtNvidia/JetsonTFBuild#4]
Thank you very much for sharing resources, but I encountered some problems in the process of compiling tensorflow. I hope you can help me to solve it. Thank you very much!
code
This bash script will install TensorFlow       
branch on a Jetson system that has been setup  
by Jetpack with CUDA and cuDNN already installed.
                                               
If this is not the case then this script will  
likely fail                                    
                                               
Expect this script to take up to 6+ hours      
                                               
Writen by: Jason Tichy < jtichy@nvidia.com >   
Version 1.0: Jan 3rd, 2018                     
Version 1.1: Mar 30, 2018 Added TensorRT support
                                               
Note: TF v 1.7.0 release contains a bug for arm
because of a hardcoded x86 path in the TensorRT
Bazel script, you will need to use master to   
build with TensorRT support                    
Get:1 file:/var/cuda-repo-9-0-local  InRelease
Ign:1 file:/var/cuda-repo-9-0-local  InRelease
Get:2 file:/var/nv-tensorrt-repo-ga-cuda9.0-trt3.0.4-20180208  InRelease
Ign:2 file:/var/nv-tensorrt-repo-ga-cuda9.0-trt3.0.4-20180208  InRelease
Get:3 file:/var/visionworks-repo  InRelease
Ign:3 file:/var/visionworks-repo  InRelease
Get:4 file:/var/visionworks-sfm-repo  InRelease
Ign:4 file:/var/visionworks-sfm-repo  InRelease
Get:5 file:/var/visionworks-tracking-repo  InRelease
Ign:5 file:/var/visionworks-tracking-repo  InRelease
Get:6 file:/var/cuda-repo-9-0-local  Release [574 B]
Get:7 file:/var/nv-tensorrt-repo-ga-cuda9.0-trt3.0.4-20180208  Release [574 B]
Get:8 file:/var/visionworks-repo  Release [1,999 B]
Get:9 file:/var/visionworks-sfm-repo  Release [2,003 B]
Get:6 file:/var/cuda-repo-9-0-local  Release [574 B]
Get:10 file:/var/visionworks-tracking-repo  Release [2,008 B]
Get:7 file:/var/nv-tensorrt-repo-ga-cuda9.0-trt3.0.4-20180208  Release [574 B]
Get:8 file:/var/visionworks-repo  Release [1,999 B]                     
Get:9 file:/var/visionworks-sfm-repo  Release [2,003 B]                   
Get:10 file:/var/visionworks-tracking-repo  Release [2,008 B]             
Hit:11 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports xenial-updates InRelease                    
Hit:12 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports xenial-security InRelease
Hit:13 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports xenial-backports InRelease
Hit:14 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports xenial InRelease
Hit:18 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease      
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
htop is already the newest version (2.0.1-1ubuntu1).
mlocate is already the newest version (0.26-1ubuntu2).
ncdu is already the newest version (1.11-1build1).
The following packages were automatically installed and are no longer required:
  apt-clone archdetect-deb dmeventd dmraid dpkg-repack gir1.2-timezonemap-1.0 gir1.2-xkl-1.0 kpartx
  kpartx-boot libappstream3 libdebian-installer4 libdevmapper-event1.02.1 libdmraid1.0.0.rc16
  liblockfile-bin liblockfile1 liblvm2app2.2 liblvm2cmd2.02 libparted-fs-resize0 libreadline5
  lockfile-progs lvm2 os-prober pmount python3-icu python3-pam rdate ubiquity-casper
  ubiquity-ubuntu-artwork ubuntu-core-launcher
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
Build label: 0.10.0- (@non-git)
Build target: bazel-out/arm-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 14 13:01:18 +50385 (1527841400478)
Build timestamp: 1527841400478
Build timestamp as int: 1527841400478
M	tensorflow/contrib/lite/kernels/internal/BUILD
M	third_party/png.BUILD
Already on 'master'
Your branch is up-to-date with 'origin/master'.
error: patch failed: tensorflow/contrib/lite/kernels/internal/BUILD:20
error: tensorflow/contrib/lite/kernels/internal/BUILD: patch does not apply
error: patch failed: third_party/png.BUILD:35
error: third_party/png.BUILD: patch does not apply
nvidia@tegra-ubuntu:~/JetsonTFBuild-master$ bazel clean

**Comment by zkhodzhaev** [comment]
I have exactly the same problem. The first time I was installing, it went well but I was out of space. The next time I tried to install I got the same error.

Any idea how to fix it ?

**Comment by idavis** [comment]
@Zulfidin @JasonAtNvidia  I have a [fork to do this](https://github.com/idavis/JetsonTFBuild/commit/a1ef26ffc8af772d3bf51cf666336058ee2a33f9) but I have to add a couple of things which I didn't want to recommend mainline without @JasonAtNvidia taking a look. The TensorRT install path doesn't work on my PX2 so I have to hard code it.

**Comment by JasonAtNvidia** [comment]
I'm taking a look at the script soon and will be adding more automation pieces.  @idavis  Your changes look good.  I will probably use them as inspiration as I add a few more automation pieces into the code.  I hope to do a rebase soon with something more robust to failure.  The original version of this script wasn't a script at all but just a list of how-to, that list became a bash script, that script has grown to include automation.  Tensorflow keeps changing things at a rate I cannot keep up with.

**Comment by idavis** [comment]
@JasonAtNvidia Agreed. It is hard to keep up and figure out which versions of bazel, which defines, etc keep changing. Have you tried cross-compiling TF for Jetson?

**Comment by JasonAtNvidia** [comment]
@idavis It is my understanding that I cannot cross compile because I would need the ARM source for CUDA, cuDNN, and TensorRT on the computer I am trying to cross compile for.  The 4-5 hour compile time on the Jetson itself isn't breaking me down to a point where I am trying to do it on my big workstation yet.
