### ISSUE TITLE
License

### ISSUE THREAD

**Issue by idavis** [JasonAtNvidia/JetsonTFBuild#5]
Can you please add a license to the scripts? I would like to contribute, but I need the scripts to be licensed first.

Thank you,

Ian

**Comment by idavis** [comment]
Hello, @JasonAtNvidia , is there any chance we add a license to the scripts/repo?

Thank you,

Ian

**Comment by idavis** [comment]
Sorry I forgot to mention, @JasonAtNvidia , I know how to fix [Issue 4](https://github.com/JasonAtNvidia/JetsonTFBuild/issues/4) but I need a license to contribute.

**Comment by JasonAtNvidia** [comment]
@idavis I hadn't planned on licensing anything other than passing forward the licenses required by the software we are building.  To me this project is just a bash script that makes the things people can do for themselves much more simple.  Feel free to change or recommend any changes you'd like.  Or perhaps there is a license that allows people to freely use whatever you'd like for me to add?

**Comment by idavis** [comment]
The OSI approved [MIT license](https://opensource.org/licenses/MIT) is very popular and gives a lot of freedom. Right now, you are [retaining all rights and giving no reuse](https://choosealicense.com/no-permission/) through an implicit lack of license.

**Comment by JasonAtNvidia** [comment]
@idavis I believe I updated the project and included the MIT license as would normally be included.  Let me know if I did something bad.

**Comment by idavis** [comment]
Thank you very much! I think the only thing missing is the license holder next to the year :)

This repo was incredibly handy. Thank you for publishing this.

**Comment by idavis** [comment]
@JasonAtNvidia Thank you. I'll close this and get a PR to you when I can. I'm also trying to get a fix in for TensorFlow to simplify things a little.

**Comment by zkhodzhaev** [comment]
So, is there any solution to Issue 4 ?
