### ISSUE TITLE
Building Bazel Error

### ISSUE THREAD

**Issue by zkhodzhaev** [JasonAtNvidia/JetsonTFBuild#7]
The Error looks like:
🍃  Building Bazel from scratch......
🍃  Building Bazel with Bazel.
INFO: Analysed target //src:bazel (198 packages loaded).
INFO: Found 1 target...
INFO: From Compiling src/main/cpp/blaze_util_posix.cc:
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::Daemonize(const char*, bool)':
src/main/cpp/blaze_util_posix.cc:218:28: warning: ignoring return value of 'int dup(int)', declared with attribute warn_unused_result [-Wunused-result]
   (void) dup(STDOUT_FILENO);  // stderr (2>&1)
                            ^
src/main/cpp/blaze_util_posix.cc: In function 'void blaze::DieAfterFork(const char*)':
src/main/cpp/blaze_util_posix.cc:265:49: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, message, strlen(message));  // strlen should be OK
                                                 ^
src/main/cpp/blaze_util_posix.cc:266:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, ": ", 2);
                                ^
src/main/cpp/blaze_util_posix.cc:267:59: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, error_string, strlen(error_string));
                                                           ^
src/main/cpp/blaze_util_posix.cc:268:32: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
   write(STDERR_FILENO, "\n", 1);
                                ^
src/main/cpp/blaze_util_posix.cc: In function 'uint64_t blaze::AcquireLock(const string&, bool, bool, blaze::BlazeLock*)':
src/main/cpp/blaze_util_posix.cc:667:30: warning: ignoring return value of 'int ftruncate(int, __off_t)', declared with attribute warn_unused_result [-Wunused-result]
   (void) ftruncate(lockfd, 0);
                              ^
src/main/cpp/blaze_util_posix.cc: At global scope:
src/main/cpp/blaze_util_posix.cc:404:15: warning: 'std::__cxx11::string blaze::RunProgram(const string&, const std::vector<std::__cxx11::basic_string<char> >&)' defined but not used [-Wunused-function]
 static string RunProgram(const string& exe,
               ^
INFO: From JavacBootstrap src/main/java/com/google/devtools/build/lib/shell/libshell-skylark.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
INFO: From JavacBootstrap src/java_tools/singlejar/java/com/google/devtools/build/singlejar/libbootstrap.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
1 warning
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libskylark-deps.jar [for host]:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
INFO: From JavacBootstrap src/java_tools/buildjar/java/com/google/devtools/build/buildjar/libbootstrap.jar [for host]:
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
Note: src/java_tools/buildjar/java/com/google/devtools/build/buildjar/instrumentation/JacocoInstrumentationProcessor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
INFO: From Executing genrule //src/java_tools/junitrunner/java/com/google/testing/coverage:Jacoco_jarjar:
Aug 06, 2018 8:12:02 PM com.tonicsystems.jarjar.transform.JarTransformer transform
INFO: Transforming archive ZipArchive(/tmp/bazel_sYhd3tRU/out/execroot/io_bazel/bazel-out/arm-opt/bin/src/java_tools/junitrunner/java/com/google/testing/coverage/JacocoCoverage_deploy.jar)
Aug 06, 2018 8:12:10 PM com.tonicsystems.jarjar.transform.jar.ClassTransformerJarProcessor process
WARNING: Failed to read class module-info.class: java.lang.RuntimeException
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_devtools_build_v1_build_events_proto:
google/devtools/build/v1/build_events.proto: warning: Import google/rpc/status.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_bytestream_bytestream_proto:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
INFO: From Generating Java (Immutable) proto_library @googleapis//:google_watch_v1_proto:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From SkylarkAction external/googleapis/google_watch_v1_java_grpc_srcs.jar:
google/watcher/v1/watch.proto: warning: Import google/protobuf/empty.proto but not used.
INFO: From SkylarkAction external/googleapis/google_bytestream_bytestream_java_grpc_srcs.jar:
google/bytestream/bytestream.proto: warning: Import google/protobuf/wrappers.proto but not used.
Target //src:bazel up-to-date:
  bazel-bin/src/bazel
INFO: Elapsed time: 869.737s, Critical Path: 279.19s
INFO: 1838 processes: 1556 local, 282 worker.
INFO: Build completed successfully, 2210 total actions

Build successful! Binary is here: /home/nvidia/Downloads/JetsonTFBuild-master/TensorFlow_Install/bazel/output/bazel
Cloning into 'tensorflow'...
remote: Counting objects: 398267, done.
remote: Compressing objects: 100% (140/140), done.
remote: Total 398267 (delta 63), reused 95 (delta 54), pack-reused 398071
Receiving objects: 100% (398267/398267), 183.32 MiB | 11.17 MiB/s, done.
Resolving deltas: 100% (316612/316612), done.
Checking connectivity... done.
Checking out files: 100% (12156/12156), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
PYTHON_BIN_PATH=/usr/bin/python
GCC_HOST_COMPILER_PATH=/usr/bin/gcc
CUDA_TOOLKIT_PATH=/usr/local/cuda
TF_CUDA_VERSION=9.0
TF_CUDA_COMPUTE_CAPABILITIES=5.3,6.2
CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu
TF_CUDNN_VERSION=7.0.5
Extracting Bazel installation...
You have bazel 0.13.0- (@non-git) installed.
Please upgrade your bazel installation to version 0.15.0 or higher to build TensorFlow!
Configuration finished
Creating Swap for build process
Setting up swapspace version 1, size = 8 GiB (8589930496 bytes)
no label, UUID=9616953f-d602-49fe-b48b-585c8bcaced1
Starting local Bazel server and connecting to it...
..................................
WARNING: Config value opt is not defined in any .rc file
ERROR: /home/nvidia/Downloads/JetsonTFBuild-master/TensorFlow_Install/tensorflow/WORKSPACE:21:1: Traceback (most recent call last):
	File "/home/nvidia/Downloads/JetsonTFBuild-master/TensorFlow_Install/tensorflow/WORKSPACE", line 21
		check_bazel_version_at_least("0.15.0")
	File "/home/nvidia/Downloads/JetsonTFBuild-master/TensorFlow_Install/tensorflow/tensorflow/version_check.bzl", line 47, in check_bazel_version_at_least
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.13.0- (@non-git), expected at least 0.15.0
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'android.bzl': no such package '@local_config_android//': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'android.bzl': no such package '@local_config_android//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 3.856s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

Any idea ?

**Comment by jreuben11** [comment]
see my issue: https://github.com/JasonAtNvidia/JetsonTFBuild/issues/9 - TF1.10 (current master) requires Bazel 0.15.0
you can either change the script to pull a newer Bazel, or try your luck with branch 1.19

**Comment by JasonAtNvidia** [comment]
@Zulfidin current version I uploaded builds the required bazel version for TF, try out the new updates
