### ISSUE TITLE
Bazel error

### ISSUE THREAD

**Issue by AdamAmp** [JasonAtNvidia/JetsonTFBuild#8]
I had an error when loading Tensor flow.  WE are running a TX2, it was freshly flashed with Jetpack 3.2.1.Here are the errors I am seeing:
.................................
WARNING: Config value opt is not defined in any .rc file
ERROR: /home/nvidia/JetsonTFBuild/TensorFlow_Install/tensorflow/WORKSPACE:21:1: Traceback (most recent call last):
	File "/home/nvidia/JetsonTFBuild/TensorFlow_Install/tensorflow/WORKSPACE", line 21
		check_bazel_version_at_least("0.15.0")
	File "/home/nvidia/JetsonTFBuild/TensorFlow_Install/tensorflow/tensorflow/version_check.bzl", line 47, in check_bazel_version_at_least
		fail("\nCurrent Bazel version is {}, ...))

Current Bazel version is 0.13.0- (@non-git), expected at least 0.15.0
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'android.bzl': no such package '@local_config_android//': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'android.bzl': no such package '@local_config_android//': error loading package 'external': Could not load //external package
INFO: Elapsed time: 3.549s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jreuben11** [comment]
see my issue: https://github.com/JasonAtNvidia/JetsonTFBuild/issues/9 - TF1.10 (current master) requires Bazel 0.15.0
you can either change the script to pull a newer Bazel, or try your luck with branch 1.19

**Comment by JasonAtNvidia** [comment]
@AdamAmp I have updated the script to build TF 1.10.0 and I know it works on TF 1.10.1, it goes and looks for the required bazel build for TF 1.10.0.  Sorry about that.  It is tough to keep this script up to date as quickly as TF creates new releases and updates.
