### ISSUE TITLE
Support for TensorFlow v1.10

### ISSUE THREAD

**Issue by jreuben11** [JasonAtNvidia/JetsonTFBuild#9]
issue 1: **patch failed with default branch (master, which is now v1.10)**
I see TF 1.8, 1.9 required this patch:
tf 1.8 fails on aarch64 https://github.com/tensorflow/tensorflow/issues/18643
tf 1.9 fails on aarch64 https://github.com/tensorflow/tensorflow/issues/21332
is this patch supported with Tensorflow v1.10 ?

what are the implications of commenting out this patch for v1.10?

**Comment by jreuben11** [comment]
issue 2: **TF 1.10 seems to require Bazel 0.15.0**
the script installs Bazel 0.13.0

**Comment by JasonAtNvidia** [comment]
I have updated the script to work with TF 1.10.0 and I know it also works with TF 1.10.1, hopefully this solves your issue.
